# Generated by Django 4.2.10 on 2024-02-25 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_degree_field_of_study_institution_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=4294967295)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=250)),
                ('image_url', models.ImageField(default='null', upload_to='static/group/images')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4294967295)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.group')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('LIKE', 'like'), ('COMMENT', 'comment'), ('SHARE', 'share')], max_length=10)),
                ('feedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.feed')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(default='null', upload_to='static/feed/images')),
                ('feedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.feed')),
            ],
        ),
        migrations.CreateModel(
            name='group_membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.group')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=4294967295)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.group')),
            ],
        ),
    ]
